### PR TITLE
Rename base.php to Base.php

### PR DESCRIPTION
**Pull request by szepeviktor**
https://github.com/johnbillion/args/blob/e7366bdbae35fc91b75af2c126ba0d13b7c1e854/src/Args/base.php#L10

### CODE REVIEW

**Comment by thefrosty** [comment]
Would like to see this escalated.

To avoid these composer warnings:

> Class Args\Base located in ./vendor/johnbillion/args/src/Args/base.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by szepeviktor** [comment]
@johnbillion Could you lend us a click?

**Comment by szepeviktor** [comment]
Thank you.

**Comment by thefrosty** [comment]
Thanks, now just need a new release tagged.

**Comment by johnbillion** [comment]
Are you using this library for something? :-)

**Comment by thefrosty** [comment]
I just pulled it into my package: https://packagist.org/packages/johnbillion/args/dependents?order_by=downloads 😉

**Comment by johnbillion** [comment]
Neat. I didn't expect anybody to be using this. I just tagged 0.0.3.

**Pull request merged**
