### PR TITLE
Remove scanDirectories from PHPStan config

### PR DESCRIPTION
**Pull request by szepeviktor**
PHPStan scans directories in `paths`

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please consider adding

```neon
includes:
  - vendor/phpstan/phpstan-strict-rules/rules.neon
```

**Comment by johnbillion** [comment]
The reason this is here is due to a problem with [the PHP Static Analysis extension for VS Code](https://marketplace.visualstudio.com/items?itemName=breezelin.phpstan). It doesn't actually affect this library, but it affects others such as [Authorship](https://github.com/humanmade/authorship) and [User Switching](https://github.com/johnbillion/user-switching).

When you open a single file in VS Code and it runs the PHPStan scan it does not use the value of `paths` to scan other files, which results in errors with symbols not being found. This is most noticeable when scanning the test files as it cannot find the source files referenced in the tests, nor can it find the parent test case class.

I haven't reported the problem to the extension author yet as I haven't had time to investigate where the problem lies.

**Comment by szepeviktor** [comment]
> When you open a single file in VS Code and it runs the PHPStan scan

In PHPStan world it is not possible to analyze a single file without configuration.

**Comment by szepeviktor** [comment]
Correction. It is possible using the configuration file and a command line argument

`vendor/bin/phpstan analyse src/Args/register_taxonomy.php`

and it works without `scanDirectories:`

**Comment by johnbillion** [comment]
Correct, as I said I haven't had time to look into where the problem lies exactly.

**Comment by johnbillion** [comment]
Actually that might not have been the exact issue. There is also a reason I had to manually list each file in `scanFiles` here: https://github.com/humanmade/authorship/blob/develop/phpstan.neon.dist . Can't remember off the top of my head the reason.

**Comment by szepeviktor** [comment]
It would be useful to know what command line is executed by `breeze2/vscode-phpstan`.

**Comment by szepeviktor** [comment]
> There is also a reason I had to manually list each file in `scanFiles` here:

Unfortunately there is no CI for Authorship.

**Comment by johnbillion** [comment]
CI is here: https://github.com/humanmade/authorship/actions but it might also have been an issue with the VS Code extension

**Comment by johnbillion** [comment]
https://github.com/breeze2/vscode-phpstan/blob/50d0d16809c6eb6419df1eb289b1bf1ebc89e056/src/controller.ts#L307-L334

**Comment by szepeviktor** [comment]
> [breeze2/vscode-phpstan@`50d0d16`/src/controller.ts#L307-L334](https://github.com/breeze2/vscode-phpstan/blob/50d0d16809c6eb6419df1eb289b1bf1ebc89e056/src/controller.ts#L307-L334)

Please set `configuration` and `level` to `config` and everything should be okay in VS Code.

**Pull request merged**
