### PR TITLE
Remove how-to part from LICENSE

### PR DESCRIPTION
**Pull request by szepeviktor**
Big-time friend of #37

### CODE REVIEW

**Comment by johnbillion** [comment]
What's the reason for removing this?

**Comment by szepeviktor** [comment]
This section is for the project owner who uses the license, not for users.
No one wants _Ty Coon_, nor _Gnomovision_.

**Comment by szepeviktor** [comment]
Someone wrote

> If you remove the "how to use this license," the result is no longer the GPL

https://softwareengineering.stackexchange.com/a/281951

**Comment by szepeviktor** [comment]
I am sorry.

> The preamble and **instructions** are integral parts of the GNU GPL and may not be omitted.

https://www.gnu.org/licenses/gpl-faq.html#GPLOmitPreamble

**Comment by szepeviktor** [comment]
GPL 3.0 has no _Ty Coon_
https://www.gnu.org/licenses/gpl-3.0.html#howto

**Pull request closed without merging**
